### ISSUE TITLE
Please make a proper uninstaller

### ISSUE THREAD

**Issue by xue159357** [svanheulen/genhax#2]
I select the first challenge quest and download it and it had removed the homebrew entry point but it seems like the hax still exist and is taking up space as one challenge quest. I cannot download the last challenge quest because of this. I have tried exporting the save and importing it back in but it seems like the hax is tied as DLC with the save file so it didn't work. 

Edit: I also deleted the otherapp payload in extdata using FBI but still didn't work.

**Comment by xue159357** [comment]
Found a temporary solution. If you also have another region version of MHX you can copy your character(s) over using MHX Data Manager, delete the extdata on the original one that contains the bugged DLC quest, relaunch it once to create new extdata, then finally copy the character(s) back to the orginal version.

**Comment by svanheulen** [comment]
Ah sorry. The installer was just putting the exploit in the first quest slot but if the first quest isn't saved there (which can easily happen if you install the DLC as they're released) you end up with 2 slots using the same quest ID. The fix is to just clear all the quest slots when installing.

I made a new version of the installer that fixes this: https://github.com/svanheulen/genhax_installer/releases
